HRMNet/Models/Timesheet/AddTimesheetViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HRMNet.Models.Timesheet
{
    public class AddItemViewModel
    {
        public string Id { get; set; }

        public string Start { get; set; }

        public string End { get; set; }

        public bool AllDay { get; set; }

        public string Title { get; set; }


    }

    public class RenderUpdateItemViewModel
    {
        public int Id { get; set; }

    }
}

HRMNet/Models/Timesheet/TimesheetItem.cs
using HRMNet.Models.Common;
using HRMNet.Models.Identity;
using HRMNet.Models.Positions;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace HRMNet.Models.Timesheet
{
    public class TimesheetItem: BaseEntity
    {

        //[Required(ErrorMessage = "*")]
        [Display(Name = "Title")]
        [StringLength(450)]
        public virtual string Title { get; set; }

        [Display(Name = "Description")]
        [StringLength(450)]
        public virtual string Description { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Start")]
        public virtual DateTime? Start { get; set; }

        [Display(Name = "End")]
        public virtual DateTime? End { get; set; }


        public virtual DateTime? StartTime { get; set; }

        public virtual DateTime? EndTime { get; set; }


        public virtual int? GroupId { get; set; }

        public virtual bool IsRepeated { get; set; }

        [Display(Name = "Url")]
        [StringLength(450)]
        public virtual string Url { get; set; }

        public virtual int Order { get; set; }

        [Display(Name = "All Day")]
        public virtual bool AllDay { get; set; }

        public virtual DateTime? StartRecur { get; set; }

        public virtual DateTime? EndRecur { get; set; }

        [StringLength(450)]
        public virtual string ClassName { get; set; }

        [StringLength(50)]
        public virtual string BackgroundColor { get; set; }

        [StringLength(450)]
        public virtual string BorderColor { get; set; }

        [StringLength(450)]
        public virtual string TextColor { get; set; }

        [Display(Name = "Overlap")]
        public virtual bool Overlap { get; set; }

        public virtual TimesheetItemType Type { get; set; }

        [Display(Name = "Color")]
        public virtual TimesheetItemColor Color { get; set; }

        public virtual int? ResourseId { get; set; }

        [Display(Name = "Is Public")]
        public virtual bool IsPublic { get; set; }

        public virtual Position Position { get; set; }

        [Display(Name = "Position")]
        public int? PositionId { get; set; }

        [NotMapped]
        [Display(Name = "Position/Project")]
        public string PositionProject { get; set; }

        //[NotMapped]
        //public bool IsDelete { get; set; }

        //public virtual User User { get; set; }

        //public int? UserId { get; set; }

    }
}

HRMNet/Models/Timesheet/TimesheetViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HRMNet.Models.Timesheet
{
    public class TimesheetViewModel
    {
        public int id { get; set; }

        public string title { get; set; }

        //public string groupId { get; set; }

        public bool allDay { get; set; }

        public string start { get; set; }

        public string end { get; set; }

        public string startTime { get; set; }

        public string endTime { get; set; }

        public string startRecur { get; set; }

        public string endRecur { get; set; }

        public string url { get; set; }

        //public string className { get; set; }

        public bool editable { get; set; }

        public bool overlap { get; set; }

        public string color { get; set; }

        //public string backgroundColor { get; set; }

        //public string borderColor { get; set; }

        //public string textColor { get; set; }

        public string extendedProps { get; set; }
    }
}

HRMNet/Controllers/TimesheetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HRMNet.Data;
using HRMNet.Models.Timesheet;
using Microsoft.AspNetCore.Authorization;
using System.ComponentModel;
using HRMNet.Services.Identity;
using HRMNet.Services;
using HRMNet.Models.Common;
using DNTCommon.Web.Core;
using HRMNet.Models.Positions;

namespace HRMNet.Controllers
{
    [Authorize]
    [DisplayName("Timesheet")]
    public class TimesheetsController : Controller
    {
        private readonly IUnitOfWork _uow;
        private readonly DbSet<TimesheetItem> _context;
        private readonly DbSet<Position> _position;
        public TimesheetsController(IUnitOfWork uow)
        {
            _uow = uow ?? throw new ArgumentNullException(nameof(_uow));
            _context = uow.Set<TimesheetItem>();
            _position = uow.Set<Position>();
        }

        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [DisplayName("List")]
        public IActionResult Index()
        {

            return View();

        }

        // GET: Timesheets
        public async Task<IActionResult> Items()
        {
            var query = _context.AsNoTracking();

            if (!User.IsInRole("Admin") && !User.IsInRole("Account Manager") && !User.IsInRole("Sales Operation") && !User.IsInRole("HR Manager") && !User.IsInRole("HR Specialist"))
                query = query.Where(x => x.CreatorId == CurrentUserId.Value);

            var items = await query
                    .Select(x => new TimesheetViewModel()
                    {
                        id = x.Id,
                        allDay = x.AllDay,
                        //backgroundColor = x.BackgroundColor,
                        //borderColor = x.BorderColor,
                        //className = x.ClassName,
                        color = ReturnColor(x.Color),
                        editable = true,
                        start = x.AllDay == true ? x.Start.Value.ToString("yyyy-MM-dd") : x.Start.Value.ToString("yyyy-MM-ddTHH:mm:ss"),
                        end = x.End != null ? (x.AllDay == true ? x.End.Value.ToString("yyyy-MM-dd") : x.End.Value.ToString("yyyy-MM-ddTHH:mm:ss")) : null,
                        extendedProps = "",
                        //groupId = x.GroupId.ToString(),
                        overlap = false,
                        //textColor = x.TextColor,
                        title = string.IsNullOrWhiteSpace(x.Title) ? x.Description : x.Title + (x.AllDay ? " - 1 day" : (x.End.Value - x.Start.Value).Hours + " - hour") ,
                        url = x.Url
                    }).ToListAsync();

            return Json(items);
        }

        [AjaxOnly]
        public async Task<IActionResult> RenderAddItem([FromBody] AddItemViewModel model)
        {
            var positions = _position
                .Include(x => x.Customer)
                .AsNoTracking();


            if (User.IsInRole("Developer"))
            {
                ViewData["PositionId"] = new SelectList(await positions.Select(x => new { Id = x.Id, Name = x.ProjectName }).ToListAsync(), "Id", "Name");
            }
            else
            {
                ViewData["PositionId"] = new SelectList(await positions.Select(x => new { Id = x.Id, Name = x.PositionName + " (" + x.Customer.Name + ") " }).ToListAsync(), "Id", "Name");
            }


            return PartialView("Create", model: new TimesheetItem() { Start = DateTime.Parse(model.Start), End = DateTime.Parse(model.End), Title = model.Title, AllDay = model.AllDay });
        }

        [HttpPost]
        [AjaxOnly]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [DisplayName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddItem(TimesheetItem model)
        {
            if (ModelState.IsValid)
            {

                if (model.PositionId == 0)
                    model.PositionId = null;

                //if (model.Title == null || model.Title==string.Empty)
                //    model.Title = model.Description;

                try
                {

                    if ((model.End.Value - model.Start.Value).TotalDays >= 1)
                    {
                        model.Type = TimesheetItemType.AllDay;
                        model.AllDay = true;
                    }
                    else
                    {
                        model.Type = TimesheetItemType.Small;
                        model.AllDay = false;
                    }

                    _context.Add(model);
                    var result = await _uow.SaveChangesAsync();

                    if (result > 0)
                        return Json(new { success = true, id = result, color = ReturnColor(model.Color), title = string.IsNullOrWhiteSpace(model.Title)? model.Description: model.Title });
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    throw;
                }

            }

            var positions = await _position
                .Include(x => x.Customer)
                .AsNoTracking()
                .Select(x => new { Id = x.Id, Name = x.PositionName + " (" + x.Customer.Name + ") " })
                .ToListAsync();

            ViewData["PositionId"] = new SelectList(positions, "Id", "Name");
            return PartialView("Create", model: model);
        }

        [AjaxOnly]
        public async Task<IActionResult> RenderUpdateItem([FromBody] AddItemViewModel model)
        {
            var item = await _context
                .FirstOrDefaultAsync(x => x.Id == int.Parse(model.Id));

            if (!string.IsNullOrWhiteSpace(model.End)) // resize mode
            {
                item.End = DateTime.Parse(model.End);
            }

            if (!string.IsNullOrWhiteSpace(model.Start)) // resize mode
            {
                item.Start = DateTime.Parse(model.Start);
            }

            var positions = _position
                .Include(x => x.Customer)
                .AsNoTracking();
            //.Select(x => new { Id = x.Id, Name = x.PositionName + " (" + x.Customer.Name + ") " }).ToListAsync();

            if (User.IsInRole("Developer"))
            {
                ViewData["PositionId"] = new SelectList(await positions.Select(x => new { Id = x.Id, Name = x.ProjectName }).ToListAsync(), "Id", "Name");
            }
            else
            {
                ViewData["PositionId"] = new SelectList(await positions.Select(x => new { Id = x.Id, Name = x.PositionName + " (" + x.Customer.Name + ") " }).ToListAsync(), "Id", "Name");
            }

            //ViewData["PositionId"] = new SelectList(positions, "Id", "Name");

            return PartialView("Edit", model: item);
        }

        [HttpPost]
        [AjaxOnly]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [DisplayName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateItem(TimesheetItem model, bool isDelete = false)
        {
            if (ModelState.IsValid)
            {

                if (model.PositionId == 0)
                    model.PositionId = null;

                if (isDelete) // delete mode
                {
                    if (model.Id == 0)
                        return null;

                    var item = await _context.FindAsync(model.Id);
                    _context.Remove(item);
                    var deleteResult = await _uow.SaveChangesAsync();

                    if (deleteResult > 0)
                        return Json(new { success = true, isDelete = true, id = model.Id });
                }

                if ((model.End.Value - model.Start.Value).TotalDays >= 1)
                {
                    model.Type = TimesheetItemType.AllDay;
                    model.AllDay = true;
                }
                else
                {
                    model.Type = TimesheetItemType.Small;
                    model.AllDay = false;
                }



                _context.Update(model);
                var updateResult = await _uow.SaveChangesAsync();

                if (updateResult > 0)
                {
                    return Json(new
                    {
                        success = true,
                        isDelete = false,
                        id = model.Id,
                        title =string.IsNullOrWhiteSpace(model.Title)? model.Description: model.Title,
                        color = ReturnColor(model.Color),
                        allDay = model.AllDay,
                        start = model.AllDay == true ? model.Start.Value.ToString("yyyy-MM-dd") : model.Start.Value.ToString("yyyy-MM-ddTHH:mm"),
                        end = model.End != null ? (model.AllDay == true ? model.End.Value.ToString("yyyy-MM-dd") : model.End.Value.ToString("yyyy-MM-ddTHH:mm")) : null
                    });
                }
            }

            var positions = await _position
                    .Include(x => x.Customer)
                    .AsNoTracking().Select(x => new { Id = x.Id, Name = x.PositionName + " (" + x.Customer.Name + ") " }).ToListAsync();

            ViewData["PositionId"] = new SelectList(positions, "Id", "Name");
            return PartialView("Edit", model: model);
        }

        [AjaxOnly]
        [HttpPost]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [DisplayName("Delete")]
        public async Task<IActionResult> DeleteItem(TimesheetItem model)
        {
            if (model.Id == 0)
                return null;

            var item = await _context.FindAsync(model.Id);
            _context.Remove(item);
            var deleteResult = await _uow.SaveChangesAsync();

            if (deleteResult > 0)

HRMNet/Views/Timesheets/Edit.cshtml
@model TimesheetItem

@inject IHtmlLocalizerFactory HtmlLocalizerFactory
@{ var sharedLocalizer = HtmlLocalizerFactory.Create(
       baseName: "SharedResource",
       location: "HRMNet"); }

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <div class="row">
                <h4 class="modal-title">@sharedLocalizer["Update"]</h4>

                @*<div class="col-md-2">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    </div>*@

            </div>

        </div>
        <form id="frmEdit" asp-action="UpdateEvent" method="post" class="form-horizontal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="modal-body">
                <div class="row">
                    @if (Model.AllDay)
                    {
                        <div class="col-md-12">
                            @Model.Start.Value.ToString("yyyy/MM/dd")
                        </div>
                    }
                    else
                    {
                        <div class="col-md-12">
                            @Model.Start.Value.ToString("yyyy/MM/dd HH:mm") - @Model.End.Value.ToString("yyyy/MM/dd HH:mm")
                        </div>

                    }
                </div>
                <div class="row">
                    <div class="col-md-12">

                        <label asp-for="PositionId" class="control-label"></label>
                        <select asp-for="PositionId" class="form-control" asp-items="ViewBag.PositionId">
                            <option value="0" selected>Please select ...</option>
                        </select>
                        <input type="hidden" asp-for="Title" class="form-control" />
                        <span asp-validation-for="PositionId" class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea asp-for="Description" class="form-control" rows="5"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label asp-for="Color" class="control-label"></label>
                        <select asp-for="Color" asp-items="@Html.GetEnumSelectList<TimesheetItemColor>()" class="form-control"></select>
                        <span asp-validation-for="Color" class="text-danger"></span>
                    </div>
                    @*<div class="col-md-3">
                            <label asp-for="AllDay" class="control-label"></label>
                            <input asp-for="AllDay" class="form-control">
                            <span asp-validation-for="AllDay" class="text-danger"></span>
                        </div>
                        <div class="col-md-3">
                            @if (User.IsInRole("CalendarAdmin") || User.IsInRole("Admin"))
                            {
                                <label asp-for="IsPublic" class="control-label"></label>
                                <input asp-for="IsPublic" class="form-control">
                                <span asp-validation-for="IsPublic" class="text-danger"></span>
                            }
                        </div>*@
                </div>

                <input asp-for="Start" type="hidden" />
                <input asp-for="End" type="hidden" />
                <input asp-for="Id" type="hidden" />
                <input asp-for="CreatorId" type="hidden" />

            </div>
            <div class="modal-footer">
                <button class="btn btn-info" type="submit">@sharedLocalizer["Update"]</button>
                <button class="btn" data-dismiss="modal" aria-hidden="true">@sharedLocalizer["Cancel"]</button>
            </div>
        </form>
        <form id="frmDelete" asp-action="DeleteItem" asp-controller="Timesheets" method="post" class="form-horizontal">
            <div class="modal-footer">
                <input id="deleteId" name="Id" value="@Model.Id" type="hidden" />
                <input id="start1" name="Start" asp-for="Start" type="hidden" />
                <input name="IsDelete" id="IsDelete" type="hidden" value="true" />
                <button class="btn btn-danger" type="submit">@sharedLocalizer["Delete from timesheet"]</button>
            </div>
        </form>
    </div>
</div>

<script>
    $(function () {
        $("body").on('change', '#PositionId', function () {    // 2nd (B)
            debugger;
            $('#Title').val($("#PositionId option:selected").text());
        });
    });
</script>

HRMNet/Views/Timesheets/Index.cshtml
@using System.Globalization;

<div style="padding:15px;" id='calendar'></div>

@section Styles
    {
    <link href="~/fullcalendar/packages/core/main.css" rel='stylesheet' />
    <link href="~/fullcalendar/packages/daygrid/main.css" rel='stylesheet' />
    <link href="~/fullcalendar/packages/timegrid/main.css" rel='stylesheet' />
    <link href="~/fullcalendar/packages/list/main.css" rel='stylesheet' />

    <style>
        .fc-sun {
            background-color: #E8EEF7;
        }

        .fc-sat {
            background-color: #E8EEF7;
        }
        /*#calendar {
            max-width: 900px;
            margin: 0 auto;
        }*/
    </style>
}

@inject IHtmlLocalizerFactory HtmlLocalizerFactory
@{ var sharedLocalizer = HtmlLocalizerFactory.Create(
           baseName: "SharedResource",
           location: "HRMNet");

    var currentCulture = CultureInfo.CurrentCulture.Name == "tr-TR" ? "tr" : "en";


}


@section Scripts
    {
    <script src="~/fullcalendar/packages/core/main.js"></script>
    <script src="~/fullcalendar/packages/interaction/main.js"></script>
    <script src="~/fullcalendar/packages/daygrid/main.js"></script>
    <script src="~/fullcalendar/packages/timegrid/main.js"></script>
    <script src="~/fullcalendar/packages/list/main.js"></script>
    <script src="~/fullcalendar/packages/core/locales/tr.js"></script>
    <script src="~/js/jquery.bootstrap-modal-ajax-form.js"></script>
    <script src="~/adminlte/plugins/blockui/jquery.blockUI.js"></script>
    <script>


        //const workSpec = [
        //    {
        //        daysOfWeek: [1, 2, 3, 4, 5],
        //        startTime: '08:00',
        //        endTime: '19:00'
        //    }
        //];

        //const workMin = workSpec.map(item => item.startTime).sort().shift()
        //const workMax = workSpec.map(item => item.endTime).sort().pop()
        //const workDays = [new Set(workSpec.flatMap(item => item.daysOfWeek))]
        //const hideDays = [...Array(7).keys()].filter(day => !workDays.includes(day))


        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
        plugins: ['interaction', 'dayGrid', 'timeGrid', 'list'],
        header: {
        left: 'prev,next today',
        center: 'title',
            right: 'dayGridMonth,timeGridWeek,timeGridDay' //dayGridWeek,dayGridDay
      },
        locale: '@currentCulture',
        minTime: "09:00:00",
        maxTime: "18:00:00",
        slotDuration: "00:15:00",
        slotLabelInterval: "01:00:00",
        //hiddenDays: [6, 7],
        //weekends: false,
        //businessHours: {
        //    // days of week. an array of zero-based day of week integers (0=Sunday)
        //    daysOfWeek: [1, 2, 3, 4, 5], // Monday - Thursday

        //    startTime: '8:00', // a start time (10am in this example)
        //    endTime: '19:00', // an end time (6pm in this example)
        //},
      selectable: true,
      selectMirror: true,
      //firstDay:1,
      //dir:'rtl',
      defaultDate: '@DateTime.Now.ToString("yyyy-MM-dd")',
      navLinks: true, // can click day/week names to navigate views
      weekNumbers: true,
      weekNumbersWithinDays: true,
      weekNumberCalculation: 'ISO',
      editable: true,
      eventLimit: true, // allow "more" link when too many events
      events: {
          url: '/Timesheets/Items',
          method: 'GET',
          failure: function() {
              alert('@sharedLocalizer["There was an error while fetching events!"]');
          }
      },
        eventClick: function (info) {
          $.blockUI({ message: '<h6>@sharedLocalizer["Please Wait ..."]</h6>' });
          info.jsEvent.preventDefault(); // don't let the browser navigate
          $.bootstrapModalAjaxForm({
              postUrl: '@Url.Action("UpdateItem", "Timesheets")',
              renderModalPartialViewUrl: '@Url.Action("RenderUpdateItem", "Timesheets")',
              renderModalPartialViewData: JSON.stringify({"Id": info.event.id }),
              loginUrl: '/login',
              beforePostHandler: function () {

              },
              completeHandler: function (result) {
                  $.unblockUI();
                  var evnt = calendar.getEventById(result.id);
                  if (result.isDelete)
                  {
                      evnt.remove();
                  }
                  else {
                      evnt.setProp('title', result.title);
                      evnt.setProp('color', result.color);
                      evnt.setProp('allDay', result.allDay);
                  }
              },
              errorHandler: function () {
                  $.unblockUI();
                  alert('@sharedLocalizer["Updating timesheet failed"]');
              }
          });
            $.unblockUI();
      },
        select: function (arg) {
            $.blockUI({ message: '<h6>@sharedLocalizer["Please Wait ..."]</h6>' });
          $.bootstrapModalAjaxForm({
              postUrl: '@Url.Action("AddItem", "Timesheets")',
              renderModalPartialViewUrl: '@Url.Action("RenderAddItem", "Timesheets")',
              renderModalPartialViewData: JSON.stringify({ "Start": arg.start.toISOString(), "End": arg.end.toISOString(), "AllDay": arg.allDay,"Title":"" }),
              loginUrl: '/login',
              beforePostHandler: function () {
              },
              completeHandler: function (result) {
                  $.unblockUI();

                  calendar.addEvent({
                      id: result.id,
                      title: result.title,
                      start: arg.start,
                      end: arg.end,
                      allDay: arg.allDay,
                      color: result.color
                  });
              },
              errorHandler: function () {
                  $.unblockUI();
                  alert('@sharedLocalizer["Adding timesheet failed"]');
              }
          });
            $.unblockUI();
          calendar.unselect();
      },
        eventDrop: function (info) {
            $.blockUI({ message: '<h6>@sharedLocalizer["Please Wait ..."]</h6>' });
          $.bootstrapModalAjaxForm({
              postUrl: '@Url.Action("UpdateItem", "Timesheets")',
              renderModalPartialViewUrl: '@Url.Action("RenderUpdateItem", "Timesheets")',
              renderModalPartialViewData: JSON.stringify({
                  "Id": info.event.id,
                  "Start": info.event.start.toISOString(),
                  "End": info.event.end.toISOString(),
              }),
              loginUrl: '/login',
              beforePostHandler: function () {
              },
              completeHandler: function (result) {

                  $.unblockUI();
                  var evnt = calendar.getEventById(result.id);
                  if (result.isDelete) {
                      evnt.remove();
                  }
                  else {
                      evnt.setProp('title', result.title);
                      evnt.setProp('color', result.color);
                      evnt.setProp('allDay', result.allDay);
                      evnt.setStart(result.start);
                      evnt.setEnd(result.end);
                  }
              },
              errorHandler: function () {
                  $.unblockUI();
                  //info.revert();
                  alert('@sharedLocalizer["Updating timesheet failed"]');
              }
          });
            $.unblockUI();
       },
        eventResize: function (info) {
            $.blockUI({ message: '<h6>@sharedLocalizer["Please Wait ..."]</h6>' });
          $.bootstrapModalAjaxForm({
              postUrl: '@Url.Action("UpdateItem", "Timesheets")',
              renderModalPartialViewUrl: '@Url.Action("RenderUpdateItem", "Timesheets")',
              renderModalPartialViewData: JSON.stringify({ "Id": info.event.id, "End": info.event.end.toISOString()}),
              loginUrl: '/login',
              beforePostHandler: function () {
              },
              completeHandler: function (result) {

                  $.unblockUI();
                  var evnt = calendar.getEventById(result.id);
                  if (result.isDelete) {
                      evnt.remove();
                  }
                  else {
                      evnt.setProp('title', result.title);
                      evnt.setProp('color', result.color);
                      evnt.setProp('allDay', result.allDay);
                  }
              },
              errorHandler: function () {
                  $.unblockUI();
                  info.revert();
                  alert('@sharedLocalizer["Updating timesheet failed"]');

              }
          });
            $.unblockUI();
        }
    });

    calendar.render();
  });


    </script>

}