HRMNet/Controllers/CandidateCoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HRMNet.Data;
using HRMNet.Models.Candidates;
using System.ComponentModel;
using Microsoft.AspNetCore.Authorization;
using HRMNet.Services.Identity;
using OfficeOpenXml;
using OfficeOpenXml.Table;
using HRMNet.Models.Learning;
using System.Text;
using Microsoft.Extensions.Localization;

namespace HRMNet.Controllers
{
    [DisplayName("Employee Courses")]
    [Authorize]
    public class CandidateCoursesController : Controller
    {
        private readonly IUnitOfWork _uow;
        private readonly DbSet<CandidateCourse> _context;
        private readonly DbSet<Candidate> _candidate;
        private readonly DbSet<Course> _course;
        private const int MaxBufferSize = 0x10000; // 64K. The artificial constraint due to win32 api limitations. Increasing the buffer size beyond 64k will not help in any circumstance, as the underlying SMB protocol does not support buffer lengths beyond 64k.
        private const string XlsxContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        private readonly IStringLocalizer _localizer;

        public CandidateCoursesController(IUnitOfWork uow, IStringLocalizerFactory stringLocalizerFactory)
        {
            _uow = uow ?? throw new ArgumentNullException(nameof(_uow));
            _context = uow.Set<CandidateCourse>();
            _candidate = uow.Set<Candidate>();
            _course = uow.Set<Course>();

            _localizer = stringLocalizerFactory.Create(
                baseName: "SharedResource",
                location: "HRMNet");
        }

        // GET: CandidateCourses
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [DisplayName("List")]
        public IActionResult Index()
        {
            var courses = _context
                .Include(c => c.Candidate)
                    .ThenInclude(x => x.StuffDetail)
                .Include(c => c.Course)
                .AsNoTracking()
                .AsEnumerable()
                .GroupBy(c => c.CandidateId)
                .Select(x => new CandidateCourse()
                {
                    EmployeeId = x.Max(z => z.Candidate?.StuffDetail?.BirthCertificateNumber),
                    CandidateId = x.Max(z => z.CandidateId),
                    CandidateDisplayName = x.Max(z => z.Candidate.Name + " " + z.Candidate.Family),
                    TotalExternal = x.Sum(z => z.CourseId.HasValue ? 0 : 1),
                    TotalInternal = x.Sum(z => z.CourseId.HasValue ? 1 : 0),
                    Total = x.Sum(z => 1),
                }).ToList();

            return View(courses);
        }

        // GET: CandidateCourses/Details/5
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [DisplayName("Detail")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var candidateCourse = await _context
                .Include(c => c.Candidate)
                .Include(c => c.Course)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (candidateCourse == null)
            {
                return NotFound();
            }

            return View(candidateCourse);
        }

        // GET: CandidateCourses/Create
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [DisplayName("Create")]
        public IActionResult Create()
        {
            ViewData["CandidateId"] = _candidate
                .Where(x => x.Status == Models.Common.CandidateStatus.VitelcoStuff)
                .AsNoTracking();

            ViewData["CourseId"] = _course
                .AsNoTracking();
            return View();
        }

        // POST: CandidateCourses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CandidateId,CourseId,Professor,Name,StartDate,EndDate,Description")] CandidateCourse candidateCourse)
        {
            if (ModelState.IsValid)
            {
                _context.Add(candidateCourse);
                await _uow.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CandidateId"] = _candidate
                .Where(x => x.Status == Models.Common.CandidateStatus.VitelcoStuff)
                .AsNoTracking();

            ViewData["CourseId"] = _course
                .AsNoTracking();

            return View(candidateCourse);
        }

        // GET: CandidateCourses/Edit/5
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [DisplayName("Edit")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var candidateCourse = await _context
                .Include(x => x.Candidate)
                .AsNoTracking()
                .FirstOrDefaultAsync(x => x.Id == id);

            if (candidateCourse == null)
            {
                return NotFound();
            }
            ViewData["CandidateId"] = _candidate
                .Where(x => x.Status == Models.Common.CandidateStatus.VitelcoStuff)
                .AsNoTracking();

            ViewData["CourseId"] = _course
                .AsNoTracking();

            return View(candidateCourse);
        }

        // POST: CandidateCourses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CandidateId,CourseId,Professor,Name,StartDate,EndDate,Description")] CandidateCourse candidateCourse)
        {
            if (id != candidateCourse.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(candidateCourse);
                    await _uow.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CandidateCourseExists(candidateCourse.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CandidateId"] = new SelectList(_candidate, "Id", "DisplayName", candidateCourse.CandidateId);
            ViewData["CourseId"] = new SelectList(_course, "Id", "Id", candidateCourse.CourseId);
            return View(candidateCourse);
        }

        // GET: CandidateCourses/Delete/5
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [DisplayName("Delete")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var candidateCourse = await _context
                .Include(c => c.Candidate)
                .Include(c => c.Course)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (candidateCourse == null)
            {
                return NotFound();
            }

            return View(candidateCourse);
        }

        // POST: CandidateCourses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var candidateCourse = await _context.FindAsync(id);
            _context.Remove(candidateCourse);
            await _uow.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [DisplayName("Export")]
        public async Task<IActionResult> ExportCandidatesCourses()
        {
            var courses = await _context
                .Include(c => c.Candidate)
                .Include(c => c.Course)
                .AsNoTracking()
                .ToListAsync();

            return File(ExportCandidatescoursesAsExcel(courses), XlsxContentType, "candidatescourses.xlsx");
        }

        private byte[] ExportCandidatescoursesAsExcel(List<CandidateCourse> candidatescourses)
        {
            byte[] reportBytes;
            using (var package = createCandidatesExcelPackage(candidatescourses))
            {
                reportBytes = package.GetAsByteArray();
            }

            return reportBytes;
        }

        private ExcelPackage createCandidatesExcelPackage(List<CandidateCourse> candidatescourses)
        {
            var package = new ExcelPackage();
            package.Workbook.Properties.Title = "Candidates Courses Report";
            package.Workbook.Properties.Author = "Vitelco";
            package.Workbook.Properties.Subject = "Candidates Courses Report";
            package.Workbook.Properties.Keywords = "Candidates Courses";

            var worksheet = package.Workbook.Worksheets.Add("CandidatesCourses");
            //First add the headers
            worksheet.Cells[1, 1].Value = "Name Surename";
            worksheet.Cells[1, 1].Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Left;
            worksheet.Cells[1, 2].Value = "Course";

HRMNet/Views/CandidateCourses/Create.cshtml
@model HRMNet.Models.Candidates.CandidateCourse

@{
    ViewData["Title"] = "Create";
}

@inject IHtmlLocalizerFactory HtmlLocalizerFactory
@{ var sharedLocalizer = HtmlLocalizerFactory.Create(
        baseName: "SharedResource",
        location: "HRMNet"); }


<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">@sharedLocalizer["Create"]</h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12">
                                <form asp-action="Create">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="CandidateId" class="control-label"></label>
                                                @Html.DropDownListFor(x => x.CandidateId, new SelectList(ViewBag.CandidateId, "Id", "DisplayName"), " Select ...", new { @class = "form-control" })
                                                @*<select asp-for="CandidateId" class="form-control" asp-items="ViewBag.CandidateId"></select>*@
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="CourseId" class="control-label"></label>
                                                @Html.DropDownListFor(x => x.CourseId, new SelectList(ViewBag.CourseId, "Id", "Name"), " Select ...", new { @class = "form-control" })
                                                @*<select asp-for="CourseId" class="form-control" asp-items="ViewBag.CourseId"></select>*@
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="Professor" class="control-label"></label>
                                                <input asp-for="Professor" class="form-control" />
                                                <span asp-validation-for="Professor" class="text-danger"></span>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="Name" class="control-label"></label>
                                                <input asp-for="Name" class="form-control" />
                                                <span asp-validation-for="Name" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="StartDate" class="control-label"></label>
                                                <input asp-for="StartDate" class="form-control" />
                                                <span asp-validation-for="StartDate" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label asp-for="EndDate" class="control-label"></label>
                                                <input asp-for="EndDate" class="form-control" />
                                                <span asp-validation-for="EndDate" class="text-danger"></span>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label asp-for="Description" class="control-label"></label>
                                                <textarea asp-for="Description" class="form-control"></textarea>
                                                <span asp-validation-for="Description" class="text-danger"></span>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <input type="submit" value="@sharedLocalizer["Create"]" class="btn btn-primary" />
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">

                            <a asp-action="Index">@sharedLocalizer["Back to List"]</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>

        function ClearAll() {
            $('#Name').val('');
            $('#StartDate').val('');
            $('#EndDate').val('');
            $('#Description').val('');
        }


        function fetchDetail(id) {
            $.ajax({
                type: "POST",
                url: "/Courses/GetCourseById",
                data: { id: id },
                success: function (result) {

                    //console.log(result);
                    $('#Name').val(result.name);
                    $('#StartDate').val(result.startDate);
                    $('#EndDate').val(result.endDate);
                    $('#Description').val(result.description);

                },
                error: function (response) {
                    //$.unblockUI();
                    alert('Fetching error');
                }
            });
        }

        $(document).ready(function () {

            $('#CourseId').change(function () {

                ClearAll();
                var selectedValue = $(this).val();
                //alert(selectedValue);

                if (selectedValue === '') {
                    $("#Name").prop("disabled", false);
                    $("#StartDate").prop("disabled", false);
                    $("#EndDate").prop("disabled", false);
                    $("#Description").prop("disabled", false);
                }
                else {

                    fetchDetail(selectedValue);

                    $("#Name").prop("disabled", true);
                    $("#StartDate").prop("disabled", true);
                    $("#EndDate").prop("disabled", true);
                    $("#Description").prop("disabled", true);
                }
            });
        });
    </script>
}

HRMNet/Views/CandidateCourses/Index.cshtml
@model IEnumerable<HRMNet.Models.Candidates.CandidateCourse>

@{
    ViewData["Title"] = "Index";
    var localization = CultureInfo.CurrentCulture.Name == "tr-TR" ? "https://cdn.datatables.net/plug-ins/1.11.3/i18n/tr.json" : "";

}

@section Styles
{
    <!-- DataTables -->
    <link rel="stylesheet" href="~/adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <style>
        td.details-control {
            background: url('images/details_open.png') no-repeat center center;
            cursor: pointer;
        }

        tr.shown td.details-control {
            background: url('images/details_close.png') no-repeat center center;
        }
    </style>
}

@inject IHtmlLocalizerFactory HtmlLocalizerFactory
@{ var sharedLocalizer = HtmlLocalizerFactory.Create(
         baseName: "SharedResource",
         location: "HRMNet"); }


<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">@sharedLocalizer["Employee Courses"]</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="row">
                            <div class="col-2">
                                <security-trimming asp-controller="CandidateCourses" asp-action="Create">
                                    <a asp-action="Create" class="btn btn-block btn-primary">@sharedLocalizer["Add"]</a><br />
                                </security-trimming>
                            </div>
                            <div class="col-2">
                                <security-trimming asp-controller="CandidateCourses" asp-action="ExportCandidatesCourses">
                                    <form asp-action="ExportCandidatesCourses" method="post">
                                        <button type="submit" class="btn btn-block btn-info">@sharedLocalizer["Export"]</button><br />

                                    </form>
                                </security-trimming>
                            </div>
                        </div>
                        <table id="coursesTable" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Candidate.StuffDetail.BirthCertificateNumber)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Candidate.DisplayName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.TotalInternal)
                                    </th>

                                    <th>
                                        @Html.DisplayNameFor(model => model.TotalExternal)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Total)
                                    </th>

                                    @*<th>
                                            @Html.DisplayNameFor(model => model.Course.CourseName)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.IsInternal)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Course.StartDate)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Course.EndDate)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Course.Duration)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Course.Description)
                                        </th>*@


                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td class="details-control">
                                            @Html.HiddenFor(modelItem => item.CandidateId)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.EmployeeId)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CandidateDisplayName)
                                        </td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.TotalInternal)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.TotalExternal)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Total)
                                        </td>

                                        @*<td>
                                                @if (item.CourseId > 0)
                                                {
                                                    @Html.DisplayFor(modelItem => item.Course.Name)
                                                }
                                                else
                                                {
                                                    @Html.DisplayFor(modelItem => item.Name)
                                                }

                                            </td>
                                            <td>
                                                @if (item.CourseId > 0)
                                                {
                                                    @Html.CheckBox("IsInternal", true, new { @disabled = "disabled" });
                                                }
                                                else
                                                {
                                                    @Html.CheckBox("IsInternal", false, new { @disabled = "disabled" });
                                                }
                                            </td>
                                            <td>
                                                @if (item.CourseId > 0)
                                                {
                                                    @Html.DisplayFor(modelItem => item.Course.StartDate)
                                                }
                                                else
                                                {
                                                    @Html.DisplayFor(modelItem => item.StartDate)
                                                }


                                            </td>
                                            <td>
                                                @if (item.CourseId > 0)
                                                {
                                                    @Html.DisplayFor(modelItem => item.Course.EndDate)
                                                }
                                                else
                                                {
                                                    @Html.DisplayFor(modelItem => item.EndDate)
                                                }

                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Course.Duration)
                                            </td>
                                            <td>
                                                @if (item.CourseId > 0)
                                                {
                                                    @Html.DisplayFor(modelItem => item.Course.Description)
                                                }
                                                else
                                                {
                                                    @Html.DisplayFor(modelItem => item.Description)
                                                }


                                            </td>*@

                                        <!--<td>
                                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |-->
                                        @*<a asp-action="Details" asp-route-id="@item.Id">Details</a> |*@
                                        <!--<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                        </td>-->
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts
{
    <!-- DataTables -->
    <script src="~/adminlte/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script>
        $(function () {

            var table = $('#coursesTable').DataTable({
                language: {
                    url: '@localization'
                }
                //"scrollX": true,
                //"scrollCollapse": true,
                //"columnDefs": [
                //    { className: "td-text-left", targets: "_all" },
                //    { width: "60px", targets: [0] },
                //    { width: "150px", targets: [1] },
                //    { width: "150px", targets: [2] },
                //    { width: "60px", targets: [3] },
                //    { width: "80px", targets: [4] },
                //    { width: "80px", targets: [5] },
                //    { width: "80px", targets: [6] },
                //    { width: "150px", targets: [7] },
                //    { width: "80px", targets: [8] },



                //]
            });
                //.columns.adjust().responsive.recalc();

            $('#coursesTable tbody').on('click', 'td.details-control', function () {
                var tr = $(this).closest('tr');
                var row = table.row(tr);
                var id = tr.find('#item_CandidateId').val();

                if (row.child.isShown()) {
                    // This row is already open - close it
                    row.child.hide();
                    tr.removeClass('shown');
                }
                else {
                    debugger;
                    // Open this row
                    format(id, row);
                    tr.addClass('shown');
                }
            });

            function format(d, row) {
                // `d` is the original data object for the row
                $.ajax({
                    type: "POST",
                    async: false,
                    url: "/CandidateCourses/GetCandidateCourses",
                    //contentType: "application/json;charset=utf-8",
                    data: { id: d },
                    //dataType: "json",
                    success: function (result) {
                        row.child(result).show();
                        return result;
                    },
                    error: function (response) {
                        //$.unblockUI();
                        //return "";
                        alert('Fetching Leaves got error');
                    }
                });
            }
        });

    </script>

}