HRMNet/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System.Threading.Tasks;
using System.Linq;
using DNTCommon.Web.Core;
using HRMNet.Models.ViewModel.Identity;
using HRMNet.Services.Contracts.Identity;
using System;
using HRMNet.Models.Common;

namespace HRMNet.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        private readonly ILogger<LoginController> _logger;
        private readonly IApplicationSignInManager _signInManager;
        private readonly IApplicationUserManager _userManager;
        private readonly IOptionsSnapshot<SiteSettings> _siteOptions;

        public LoginController(
            IApplicationSignInManager signInManager,
            IApplicationUserManager userManager,
            IOptionsSnapshot<SiteSettings> siteOptions,
            ILogger<LoginController> logger
            )
        {
            _signInManager = signInManager ?? throw new ArgumentNullException(nameof(_signInManager));

            _userManager = userManager ?? throw new ArgumentNullException(nameof(_signInManager));

            _logger = logger ?? throw new ArgumentNullException(nameof(_signInManager));

            _siteOptions = siteOptions ?? throw new ArgumentNullException(nameof(_siteOptions));

        }

        [NoBrowserCache]
        public IActionResult Index(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //[ValidateDNTCaptcha(CaptchaGeneratorLanguage = DNTCaptcha.Core.Providers.Language.English)]
        public async Task<IActionResult> Index(LoginViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(model.Username);
                if (user == null)
                {
                    ModelState.AddModelError(string.Empty, "Username or Password is invalid.");
                    return View(model);
                }

                if (!user.IsActive)
                {
                    ModelState.AddModelError(string.Empty, "Your account has been disabled");
                    return View(model);
                }

                if (_siteOptions.Value.EnableEmailConfirmation &&
                    !await _userManager.IsEmailConfirmedAsync(user))
                {
                    ModelState.AddModelError("", "Please check your mailbox and confirm your email!");
                    return View(model);
                }

                var result = await _signInManager.PasswordSignInAsync(
                                        model.Username,
                                        model.Password,
                                        model.RememberMe,
                                        lockoutOnFailure: true);
                if (result.Succeeded)
                {
                    
                    _logger.LogInformation(1, $"{model.Username} logged in.");
                    if (Url.IsLocalUrl(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }
                    return RedirectToAction(nameof(HomeController.Index), "Home");
                }

                if (result.RequiresTwoFactor)
                {
                    return RedirectToAction(
                        nameof(TwoFactorController.SendCode),
                        "TwoFactor",
                        new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                }

                if (result.IsLockedOut)
                {
                    _logger.LogWarning(2, $"{model.Username} is locked.");
                    return View("~/Views/TwoFactor/Lockout.cshtml");
                }

                if (result.IsNotAllowed)
                {
                    ModelState.AddModelError(string.Empty, "No entry access.");
                    return View(model);
                }

                ModelState.AddModelError(string.Empty, "Username or Password is invalid");
                return View(model);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        public async Task<IActionResult> LogOff()
        {
            var user = User.Identity.IsAuthenticated ? await _userManager.FindByNameAsync(User.Identity.Name) : null;
            await _signInManager.SignOutAsync();
            if (user != null)
            {
                await _userManager.UpdateSecurityStampAsync(user);
                _logger.LogInformation(4, $"{user.UserName} logged out.");
            }

            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
    }
}

HRMNet/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using DNTCommon.Web.Core;
using HRMNet.Data;
using HRMNet.Models.Candidates;
using HRMNet.Models.Common;
using HRMNet.Models.Identity;
using HRMNet.Models.ViewModel.Identity;
using HRMNet.Models.ViewModel.Identity.Emails;
using HRMNet.Services;
using HRMNet.Services.Contracts.Identity;
using HRMNet.Services.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace HRMNet.Controllers
{
    //[Authorize]
    [Authorize(Roles = "Admin")]
    public class RegisterController : Controller
    {
        private readonly IEmailSender _emailSender;
        //private readonly ILogger<RegisterController> _logger;
        private readonly IApplicationUserManager _userManager;
        private readonly IPasswordValidator<User> _passwordValidator;
        private readonly IUserValidator<User> _userValidator;
        private readonly IOptionsSnapshot<SiteSettings> _siteOptions;
        private readonly IApplicationSignInManager _signInManager;
        private readonly IUnitOfWork _uow;
        private readonly DbSet<Title> _title;
        public RegisterController
        (
            IUnitOfWork uow,
            IApplicationSignInManager signInManager,
            IApplicationUserManager userManager,
            IPasswordValidator<User> passwordValidator,
            IUserValidator<User> userValidator,
            IEmailSender emailSender,
            IOptionsSnapshot<SiteSettings> siteOptions
            //ILogger<RegisterController> logger
            )
        {
            _userManager = userManager;
            _userManager.CheckArgumentIsNull(nameof(_userManager));

            _passwordValidator = passwordValidator;
            _passwordValidator.CheckArgumentIsNull(nameof(_passwordValidator));

            _userValidator = userValidator;
            _userValidator.CheckArgumentIsNull(nameof(_userValidator));

            _emailSender = emailSender;
            _emailSender.CheckArgumentIsNull(nameof(_emailSender));

            //_logger = logger;
            //_logger.CheckArgumentIsNull(nameof(_logger));

            _siteOptions = siteOptions;
            _siteOptions.CheckArgumentIsNull(nameof(_siteOptions));

            _signInManager = signInManager;
            _signInManager.CheckArgumentIsNull(nameof(_signInManager));
            
            _uow = uow ?? throw new ArgumentNullException(nameof(uow));
            _title = uow.Set<Title>();

        }

        /// <summary>
        /// For [Remote] validation
        /// </summary>
        [AjaxOnly, HttpPost, ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> ValidateUsername(string username, string email)
        {
            var result = await _userValidator.ValidateAsync(
                (UserManager<User>)_userManager, new User { UserName = username, Email = email });
            return Json(result.Succeeded ? "true" : result.DumpErrors(useHtmlNewLine: true));
        }

        /// <summary>
        /// For [Remote] validation
        /// </summary>
        [AjaxOnly, HttpPost, ValidateAntiForgeryToken]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> ValidatePassword(string password, string username)
        {
            var result = await _passwordValidator.ValidateAsync(
                (UserManager<User>)_userManager, new User { UserName = username }, password);
            return Json(result.Succeeded ? "true" : result.DumpErrors(useHtmlNewLine: true));
        }

        [DisplayName("Confirm Email")]
        [AllowAnonymous]
        public async Task<IActionResult> ConfirmEmail(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return View("Error");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return View("NotFound");
            }

            var result = await _userManager.ConfirmEmailAsync(user, code);
            return View(result.Succeeded ? nameof(ConfirmEmail) : "Error");
        }

        [DisplayName("Register")]
        public async Task<IActionResult> Index(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            ViewData["TitleId"] = await _title.AsNoTracking().ToListAsync();

            return View();
        }

        public IActionResult ConfirmedRegisteration()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //[ValidateDNTCaptcha(CaptchaGeneratorLanguage = DNTCaptcha.Core.Providers.Language.Persian)]
        public async Task<IActionResult> Index(RegisterViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var user = new User
                {
                    UserName = model.Username,
                    Email = model.Email,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    PhoneNumber = model.PhoneNumber,
                    TitleId = model.TitleId
                };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    //_logger.LogInformation(3, $"{user.UserName} created a new account with password.");

                    if (_siteOptions.Value.EnableEmailConfirmation)
                    {
                        var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                        //ControllerExtensions.ShortControllerName<RegisterController>(), //todo: use everywhere .................

                        await _emailSender.SendEmailAsync(
                           email: user.Email,
                           subject: "Please Confirm your account",
                           viewNameOrPath: "~/Views/EmailTemplates/_RegisterEmailConfirmation.cshtml",
                           model: new RegisterEmailConfirmationViewModel
                           {
                               User = user,
                               EmailConfirmationToken = code,
                               EmailSignature = _siteOptions.Value.Smtp.FromName,
                               MessageDateTime = DateTime.UtcNow.ToLongDateString()
                           });

                        return RedirectToAction(nameof(ConfirmYourEmail));
                    }

                    if (Url.IsLocalUrl(returnUrl))
                    {
                        var registeredUser = await _userManager.FindByNameAsync(model.Username);
                        if (user != null)
                        {
                            var siginResult = await _signInManager.PasswordSignInAsync(
                                        model.Username,
                                        model.Password,
                                        false,
                                        lockoutOnFailure: true);

                            if (siginResult.Succeeded)
                            {
                                //_logger.LogInformation(1, $"{model.Username} logged in.");
                                return Redirect(returnUrl);
                            }
                        }
                    }

                    return RedirectToAction(nameof(ConfirmedRegisteration));
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View(model);
        }

        [AllowAnonymous]
        public IActionResult ConfirmYourEmail()
        {
            return View();
        }
    }
}

HRMNet/Views/Register/ConfirmEmail.cshtml
@{
    ViewData["Title"] = "";
}

@inject IHtmlLocalizerFactory HtmlLocalizerFactory
@{ var sharedLocalizer = HtmlLocalizerFactory.Create(
       baseName: "SharedResource",
       location: "HRMNet"); }

<div class="card mt-5">
    <div class="card-header">
        <h5 class="card-title">@ViewData["Title"]</h5>
    </div>
    <div class="card-body">
        @sharedLocalizer["Thanks"].
        @sharedLocalizer["Yout account information confirmed successfully"]
        
        @if (!User.Identity.IsAuthenticated)
        {
    <span>For login please click <a asp-controller="Login" asp-action="Index">here</a>.</span>}
    </div>
</div>

HRMNet/Views/Register/ConfirmYourEmail.cshtml
@inject IHtmlLocalizerFactory HtmlLocalizerFactory
@{ var sharedLocalizer = HtmlLocalizerFactory.Create(
        baseName: "SharedResource",
        location: "HRMNet"); }


<div class="card mt-5">
    <div class="card-header">
        <h5 class="card-title">@sharedLocalizer["Thanks"]</h5>
    </div>
    <div class="card-body">
        @sharedLocalizer["Registration is done successfully. Please check your mailbox and confirm your email."]
        
        <partial name="_PickupFolder" />
    </div>
</div>

HRMNet/Views/Register/ConfirmedRegisteration.cshtml
@inject IHtmlLocalizerFactory HtmlLocalizerFactory
@{ var sharedLocalizer = HtmlLocalizerFactory.Create(
        baseName: "SharedResource",
       location: "HRMNet"); }

<div class="card mt-5">
    <div class="card-header">
        <h5 class="card-title">@sharedLocalizer["Thanks"]!</h5>
    </div>
    <div class="card-body">
        @sharedLocalizer["Registration has been done successfully."]

        @sharedLocalizer["For login please click"] <a asp-controller="Login" asp-action="Index">@sharedLocalizer["here"]</a>.
    </div>
</div>

HRMNet/Views/Register/Index.cshtml
@model RegisterViewModel
@{ ViewData["Title"] = ""; }

@inject IHtmlLocalizerFactory HtmlLocalizerFactory
@{ var sharedLocalizer = HtmlLocalizerFactory.Create(
       baseName: "SharedResource",
       location: "HRMNet"); }

<div class="card mt-5">
    <div class="card-header">
        <h5 class="card-title">@ViewData["Title"]</h5>
    </div>
    <div class="card-body">
        <form asp-controller="Register"
              asp-action="Index"
              method="post">
            <partial name="_CustomValidationSummary" />
            <div class="form-group row">
                <label asp-for="FirstName" class="col-md-2 col-form-label text-md-left"></label>
                <div class="col-md-10">
                    <input dir="ltr" asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="LastName" class="col-md-2 col-form-label text-md-left"></label>
                <div class="col-md-10">
                    <input dir="ltr" asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Username" class="col-md-2 col-form-label text-md-left"></label>
                <div class="col-md-10">
                    <input dir="ltr" asp-for="Username" class="form-control" />
                    <span asp-validation-for="Username" class="text-danger"></span>
                    <span class="optional-label">(@sharedLocalizer["For Login"])</span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="PhoneNumber" class="col-md-2 col-form-label text-md-left"></label>
                <div class="col-md-10">
                    <input dir="ltr" asp-for="PhoneNumber" class="form-control" /> @*onblur="triggerRemoteValidation()"*@
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Email" class="col-md-2 col-form-label text-md-left"></label>
                <div class="col-md-10">
                    <input dir="ltr" asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Password" class="col-md-2 col-form-label text-md-left"></label>
                <div class="col-md-10">
                    <input dir="ltr" asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="ConfirmPassword" class="col-md-2 col-form-label text-md-left"></label>
                <div class="col-md-10">
                    <input dir="ltr" asp-for="ConfirmPassword" class="form-control" />
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="TitleId" class="col-md-2 col-form-label text-md-left"></label>
                <div class="col-md-10">
                    @Html.DropDownListFor(x => x.TitleId, new SelectList(ViewBag.TitleId, "Id", "Name"), " Select ...", new { @class = "form-control" })
                    <span asp-validation-for="TitleId" class="text-danger"></span>
                </div>
            </div>

            @*<div class="form-group row">
            <label class="col col-md-2 col-form-label text-md-left">
                Security Code
            </label>
            <div class="col col-md-10">
                <dnt-captcha asp-captcha-generator-max="30"
                             asp-captcha-generator-min="1"
                             asp-captcha-generator-language="English"
                             asp-captcha-generator-display-mode="SumOfTwoNumbers"
                             asp-font-name="Tahoma"
                             asp-font-size="20"
                             asp-refresh-button-class="fas fa-redo btn-sm"
                             asp-fore-color="#333333"
                             asp-back-color="#ccc"
                             asp-text-box-class="text-box form-control"
                             asp-text-box-template="<div class='input-group'><span class='input-group-prepend'><span class='input-group-text'><i class='fas fa-lock'></i></span></span>{0}</div>"
                             asp-validation-message-class="text-danger" />
            </div>
        </div>*@
            <div class="form-group row">
                <div class="offset-md-2 col-md-10">
                    <button type="submit" class="btn btn-info col-md-2">@sharedLocalizer["Register"]</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        function triggerRemoteValidation() {
            $('#@nameof(RegisterViewModel.Username)').removeData('previousValue');
            $('form').validate().element('#@nameof(RegisterViewModel.Username)');

            $('#@nameof(RegisterViewModel.Email)').removeData('previousValue');
            $('form').validate().element('#@nameof(RegisterViewModel.Email)');
        }
    </script>
}