HRMNet/Controllers/InventoryTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HRMNet.Data;
using HRMNet.Models.Candidates;
using Microsoft.AspNetCore.Authorization;
using HRMNet.Services.Identity;
using System.ComponentModel;

namespace HRMNet.Controllers
{
    [Authorize]
    [DisplayName("Inventories Category")]
    public class InventoryTypesController : Controller
    {
        private readonly IUnitOfWork _uow;
        private readonly DbSet<InventoryType> _context;

        public InventoryTypesController(IUnitOfWork uow)
        {
            _uow = uow ?? throw new ArgumentNullException(nameof(_uow));
            _context = uow.Set<InventoryType>();
            
        }

        // GET: InventoryTypes
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [DisplayName("List")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.AsNoTracking().ToListAsync());
        }

        // GET: InventoryTypes/Details/5
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [DisplayName("Detail")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventoryType = await _context.AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (inventoryType == null)
            {
                return NotFound();
            }

            return View(inventoryType);
        }

        // GET: InventoryTypes/Create
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [DisplayName("Create")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: InventoryTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Id,CreatorId,CreatedDateTime,CreatedByBrowserName,CreatorIp,ModifierId,ModifiedDateTime,ModifiedByBrowserName,ModifierIp")] InventoryType inventoryType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(inventoryType);
                await _uow.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(inventoryType);
        }

        // GET: InventoryTypes/Edit/5
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [DisplayName("Edit")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventoryType = await _context.FindAsync(id);
            if (inventoryType == null)
            {
                return NotFound();
            }
            return View(inventoryType);
        }

        // POST: InventoryTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Id,CreatorId,CreatedDateTime,CreatedByBrowserName,CreatorIp,ModifierId,ModifiedDateTime,ModifiedByBrowserName,ModifierIp")] InventoryType inventoryType)
        {
            if (id != inventoryType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(inventoryType);
                    await _uow.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InventoryTypeExists(inventoryType.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(inventoryType);
        }

        // GET: InventoryTypes/Delete/5
        [Authorize(Policy = ConstantPolicies.DynamicPermission)]
        [DisplayName("Delete")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var inventoryType = await _context.AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (inventoryType == null)
            {
                return NotFound();
            }

            return View(inventoryType);
        }

        // POST: InventoryTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var inventoryType = await _context.FindAsync(id);
            _context.Remove(inventoryType);
            await _uow.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InventoryTypeExists(int id)
        {
            return _context.AsNoTracking().Any(e => e.Id == id);
        }
    }
}

HRMNet/Views/InventoryTypes/Create.cshtml
@model HRMNet.Models.Candidates.InventoryType

@{
    ViewData["Title"] = "Create";
}

@inject IHtmlLocalizerFactory HtmlLocalizerFactory
@{ var sharedLocalizer = HtmlLocalizerFactory.Create(
        baseName: "SharedResource",
        location: "HRMNet"); }

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">@sharedLocalizer["Create"]</h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-6">
                                <form asp-action="Create">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="form-group">
                                        <label asp-for="Name" class="control-label"></label>
                                        <input asp-for="Name" class="form-control" />
                                        <span asp-validation-for="Name" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <input type="submit" value="@sharedLocalizer["Create"]" class="btn btn-primary" />
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">

                            <a asp-action="Index">@sharedLocalizer["Back to List"]</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

HRMNet/Views/InventoryTypes/Delete.cshtml
@model HRMNet.Models.Candidates.InventoryType

@{
    ViewData["Title"] = "Delete";
}

@inject IHtmlLocalizerFactory HtmlLocalizerFactory
@{ var sharedLocalizer = HtmlLocalizerFactory.Create(
       baseName: "SharedResource",
       location: "HRMNet"); }

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">

                    <div class="card-header">
                        <h3 class="card-title">@sharedLocalizer["Delete"]</h3>


                    </div>
                    <div class="card-body">
                        <div class="row">
                            <h4>@sharedLocalizer["Are you sure you want to delete this?"]</h4>
                            <dl class="row">
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.Name)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Name)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.CreatorId)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.CreatorId)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.CreatedDateTime)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.CreatedDateTime)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.CreatedByBrowserName)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.CreatedByBrowserName)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.CreatorIp)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.CreatorIp)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.ModifierId)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.ModifierId)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.ModifiedDateTime)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.ModifiedDateTime)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.ModifiedByBrowserName)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.ModifiedByBrowserName)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.ModifierIp)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.ModifierIp)
                                </dd>
                            </dl>

                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <form asp-action="Delete">
                                <input type="hidden" asp-for="Id" />
                                <input type="submit" value="@sharedLocalizer["Delete"]" class="btn btn-danger" /> |
                                <a asp-action="Index">@sharedLocalizer["Back to List"]</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

HRMNet/Views/InventoryTypes/Details.cshtml
@model HRMNet.Models.Candidates.InventoryType

@{
    ViewData["Title"] = "Details";
}

@inject IHtmlLocalizerFactory HtmlLocalizerFactory
@{ var sharedLocalizer = HtmlLocalizerFactory.Create(
        baseName: "SharedResource",
        location: "HRMNet"); }


<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">@sharedLocalizer["Detail"]</h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <dl class="row">
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.Name)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Name)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.CreatorId)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.CreatorId)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.CreatedDateTime)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.CreatedDateTime)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.CreatedByBrowserName)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.CreatedByBrowserName)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.CreatorIp)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.CreatorIp)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.ModifierId)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.ModifierId)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.ModifiedDateTime)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.ModifiedDateTime)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.ModifiedByBrowserName)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.ModifiedByBrowserName)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.ModifierIp)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.ModifierIp)
                                </dd>
                            </dl>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <a asp-action="Edit" asp-route-id="@Model.Id">@sharedLocalizer["Edit"]</a> |
                            <a asp-action="Index">@sharedLocalizer["Back to List"]</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

HRMNet/Views/InventoryTypes/Edit.cshtml
@model HRMNet.Models.Candidates.InventoryType

@{
    ViewData["Title"] = "Edit";
}

@inject IHtmlLocalizerFactory HtmlLocalizerFactory
@{ var sharedLocalizer = HtmlLocalizerFactory.Create(
       baseName: "SharedResource",
       location: "HRMNet"); }


<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">@sharedLocalizer["Edit"]</h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-6">
                                <form asp-action="Edit">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="form-group">
                                        <label asp-for="Name" class="control-label"></label>
                                        <input asp-for="Name" class="form-control" />
                                        <span asp-validation-for="Name" class="text-danger"></span>
                                    </div>
                                    <input type="hidden" asp-for="Id" />
                                    
                                    <div class="form-group">
                                        <input type="submit" value="@sharedLocalizer["Save"]" class="btn btn-primary" />
                                        |<a asp-action="Index" class="btn btn-default">@sharedLocalizer["Cancel"]</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    

                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HRMNet/Views/InventoryTypes/Index.cshtml
@model IEnumerable<HRMNet.Models.Candidates.InventoryType>

@{
    ViewData["Title"] = "Index";
}

@section Styles
{
    <!-- DataTables -->
    <link rel="stylesheet" href="~/adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link href="~/wwwroot/css/dataTables.checkboxes.css" />
}

@inject IHtmlLocalizerFactory HtmlLocalizerFactory
@{ var sharedLocalizer = HtmlLocalizerFactory.Create(
           baseName: "SharedResource",
          location: "HRMNet");
    var localization = CultureInfo.CurrentCulture.Name == "tr-TR" ? "https://cdn.datatables.net/plug-ins/1.11.3/i18n/tr.json" : "";

}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">@sharedLocalizer["Inventory Categories"]</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <form id="frm-example" asp-action="DeleteMultiple" method="POST">
                            <div class="row">
                                <div class="col-2">
                                    <security-trimming asp-controller="InventoryTypes" asp-action="Create">
                                        <a asp-action="Create" class="btn btn-block btn-primary">@sharedLocalizer["Add"]</a>
                                    </security-trimming>
                                </div>

                                @*<div class="col-2">
                                        <button type="submit" class="btn btn-block btn-danger">@sharedLocalizer["Delete All"]</button><br />
                                    </div>*@
                            </div>
                            <br />
                            <table id="inventoryTypesTable" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Name)
                                        </th>
                                        @*<th>
                                                @Html.DisplayNameFor(model => model.CreatorId)
                                            </th>

                                            <th>
                                                @Html.DisplayNameFor(model => model.ModifierId)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.ModifiedDateTime)
                                            </th>*@

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td></td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Name)
                                            </td>
                                            @*<td>
                                                    @Html.DisplayFor(modelItem => item.CreatorId)
                                                </td>

                                                <td>
                                                    @Html.DisplayFor(modelItem => item.ModifierId)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.ModifiedDateTime)
                                                </td>*@

                                            <td>
                                                <security-trimming asp-controller="InventoryTypes" asp-action="Edit">
                                                    <a asp-action="Edit" asp-route-id="@item.Id">@sharedLocalizer["Edit"]</a> |
                                                </security-trimming>
                                                @*<a asp-action="Details" asp-route-id="@item.Id">Details</a> |*@
                                                <security-trimming asp-controller="InventoryTypes" asp-action="Delete">
                                                    <a asp-action="Delete" asp-route-id="@item.Id">@sharedLocalizer["Delete"]</a>
                                                </security-trimming>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts
{
    <!-- DataTables -->
    <script src="~/adminlte/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/js/dataTables.checkboxes.min.js"></script>
    <script>
        $(document).ready(function () {


            var table = $('#inventoryTypesTable').DataTable({
                language: {
                    url: '@localization'
                },
                'columnDefs': [
                    {
                        'targets': 0,
                        'checkboxes': {
                            'selectRow': true
                        },
                        "orderable": false
                    }
                ],
                'select': {
                    'style': 'multi'
                },
                //'order': [[1, 'asc']]
            });

        });

    </script>

}